Entions
iitis/polymer_entropy pull request #24
Opened 2022-04-23 19:19 UTC by soycapitan

2022-04-24 18:33 UTC, soycapitan commented
I have pushed more changes to fix some of our broken angles definitions, mainly to point that 14 angles are within single mer. Also changed column manipulation that proved to be broken because of my poor understanding of some python internals :(

![Albumin+CS6_8_analysis_Na_hist2D_ϕ₁₄_ψ₁₄](https://user-images.githubusercontent.com/11042812/164990959-6dee3e78-90dc-40e3-876e-a955a82fbc2d.png)
Now histograms that should contain 24k data points do so.

Updated plots are available at gdrive in [PR24 r2](https://drive.google.com/drive/folders/1tIijxO97sHKC200ARBKmbcViwFHy7WEs?usp=sharing) directory.

The same command was used for plotting:
```
$python3 src/plot.py --datafolder data3 --complex 'Albumin+CS6'
```

To double-check that we are calculating the right things I have created `list_columns(self):` method and raised #25

2022-04-25 07:11 UTC, kdomino requested changes

2022-04-25 07:11 UTC, kdomino commented on src/experiment.py
> +        plt.title(f"{self} - Subsequent mers angles, n={n_datapoints}")
we can filter out analysis in f"{self}. We an also remove: "Subsequent mers angles" (I know I suggested it at the first place). The best  will be something like:   Albumin+CS6_realization:1_ion:Mg  or similar

2022-04-25 07:17 UTC, soycapitan commented on src/experiment.py
> +                        if angle.endswith('₁₃'):
Yes, it appears multiple times and I am thinking about using Python generators for this to keep it cleaner.

We need to _somehow_ (and this is probably not the best way) those angles as angles `13` are measured **between** consecutive mers and angles `14` are **inside** one mer, hence the difference implied in meaning and number of such angles (n-1 angles for angles between mers)/

2022-04-25 07:19 UTC, soycapitan commented on src/experiment.py
> +                        if angle.endswith('₁₃'):
I propose to create an issue out of recurring `if angle.endswith('₁₃'):` test not to impede ingesting working code.

2022-04-25 07:21 UTC, kdomino commented on src/experiment.py
> +                        if angle.endswith('₁₃'):
Ok I see. Perhaps for now making the function ```is_angle_between_mers``` or something

2022-04-25 14:30 UTC, soycapitan commented
@kdomino ready for next review round

2022-04-26 06:28 UTC, merged